### ISSUE TITLE
Error on XP SP gui_getwindows

### ISSUE THREAD

**Issue by HerveRICHON** [OrchardSoftware/4D-Win32API#11]
Hello,

We have one error with RegDeleteKeyExA in library ADVAPI32.dll on windows XP.
![errwin322](https://cloud.githubusercontent.com/assets/4999292/7960592/0bb12508-0a02-11e5-8c49-8eb4e990b8e3.png)
![errwin321](https://cloud.githubusercontent.com/assets/4999292/7960591/0bafc366-0a02-11e5-8d83-56e0c5b6b346.png)
Regards
Hervé RICHON

**Comment by wjford** [comment]
We have a fix in the works for this issue that should be released soon. Version 6.6.0 was the version that introduced this issue. Versions 6.5.1 and older still continue to work with Windows XP.

**Comment by wjford** [comment]
This issue has been fixed in version 6.6.2

**Comment by HerveRICHON** [comment]
Madame, Monsieur,

Je serai absent  du 20 Juillet au 9 Août  prochain.

En cas d’urgence, je vous remercie de bien vouloir adresser votre demande au :
 
- Service administratif ou commercial : 
 
01 30 58 18 00 / info@ressources-si.fr / contact@ressources-si.fr
 
- ou au Service assistance : 
 
0 811 700 226 / assistance@ressources-si.fr
 
 
Dans le cas contraire, je vous contacterai dès mon retour.

Cordialement,

Hervé Richon
 
Logiciels Arc en Ciel L@Billetterie 
RESSOURCES SI 
http://www.ressources-si.fr

2, rue Hélène Boucher
78 286 GUYANCOURT CEDEX - France
France 
Tél. général : +33 1 30 58 18 00 
Tél. assistance : 0 811 700 226
Fax : +33 1 34 60 13 45 
Email général : info@ressources-si.fr 
Email assistance :  assistance@ressources-si.fr 
Email commercial : contact@ressources-si.fr
