### ISSUE TITLE
Issue on quit

### ISSUE THREAD

**Issue by OrchardSoftware** [OrchardSoftware/4D-Win32API#12]
There is an issue with Win32API when quitting a built server running on a Windows server 2008R2 and newer.  This is in 4D v14, I don’t have older ones in production to test with.  The error exists in all versions of the plugin, including 6.6.2

Here is the error from the windows crash event:

Problem signature:
  Problem Event Name:                        BEX64
  Application Name:                             Xsitra_14_R5.exe
  Application Version:                           14.5.0.0
  Application Timestamp:                     550b8fc7
  Fault Module Name:                          Win32API.4DX_unloaded
  Fault Module Version:                        0.0.0.0
  Fault Module Timestamp:                  559c1fb2
  Exception Offset:                                0000000011924720
  Exception Code:                                  c0000005
  Exception Data:                                   0000000000000008
  OS Version:                                          6.1.7601.2.1.0.272.7
  Locale ID:                                             1033
  Additional Information 1:                  cd2c
  Additional Information 2:                  cd2c5acc3b54640cde0fc16563f2384a
  Additional Information 3:                  ab12
  Additional Information 4:                  ab121385397f44a9ddb4effa92aefd54

**Comment by wjford** [comment]
This issue has been fixed in version 6.6.2.
