### ISSUE TITLE
Mac equivalent to sys_HashText

### ISSUE THREAD

**Issue by leehinde** [OrchardSoftware/4D-Win32API#14]
Is there a Mac equiv to sys_HashText that you might be aware of?

Otherwise i have to go buy a PC. :-)

**Comment by wjford** [comment]
I'm not sure about a Mac equivalent, but it should be possible to generate SHA2 hashes with PHP Execute in 4D. 

http://doc.4d.com/4Dv13/4D/13.6/PHP-Execute.301-2502499.en.html
http://php.net/manual/en/function.hash.php
