### ISSUE TITLE
Compatibility with 4D v17 R6 64-bit

### ISSUE THREAD

**Issue by issameljohri** [OrchardSoftware/4D-Win32API#37]
I'm planning to convert my 4D database to 64-bit system, my database use Win32API plugin.
Is Win32API compatible with 64-bit system ?
Thanks

**Comment by dwaddell** [comment]
Yes and no, it'll work with a 64-bit system but not every call has been fully vetted.

**Comment by datawright** [comment]
gui_LoadBackground is not working in v17 64 bit mode. Error code 0 is returned and the background doesn't change. It works fine in 32 bit mode.

**Comment by dwaddell** [comment]
Hello,

We have just migrated to v18 as well and in the process we recreated this plugin. We have not release it yet but our Testing group has been using it. We just made the repository public here: https://github.com/OrchardSoftware/4D-Win64API/releases/tag/v18

It should be noted that we fully recreated the plugin and we only migrated commands that we use. We spent a lot of time trying to eliminate calls that could be done another way, like with native 4D commands. If there are commands that you use that didn't make the migration you could pull the gui_loadBackGround and put it in the old plugin and it should work just fine. Or update the open-sourced v18 compatible version.

Hope this helps,
Drew
