### ISSUE TITLE
gui_LoadBackGround not working for  v18.4 64bit

### ISSUE THREAD

**Issue by kitakoke** [OrchardSoftware/4D-Win32API#40]
Hello dear,
I am very grateful to this plugin.
Actually, I recently migrated to v18.4, but gui_loadBackGround doesn't work on Windows10 pro 20H2.
I would appreciate any advice.

**Comment by dwaddell** [comment]
Hello,

We have just migrated to v18 as well and in the process we recreated this plugin.  We have not release it yet but our Testing group has been using it.  We just made the repository public here: https://github.com/OrchardSoftware/4D-Win64API/releases/tag/v18

It should be noted that we fully recreated the plugin and we only migrated commands that we use.  We spent a lot of time trying to eliminate calls that could be done another way, like with native 4D commands.  If there are commands that you use that didn't make the migration you could pull the gui_loadBackGround and put it in the old plugin and it should work just fine.  Or update the open-sourced v18 compatible version.

Hope this helps,
Drew

**Comment by kitakoke** [comment]
Thanks a lot,it worked well!

Best regards,
Kouji Kitamura.
