### ISSUE TITLE
Add ability to detect if 4D is running within a virtual machine

### ISSUE THREAD

**Issue by wjford** [OrchardSoftware/4D-Win32API#9]
It has been requested that virtual machine detection is added to Win32API. Currently, Orchard Software is unable to spend any development time on this request. 

http://www.codeproject.com/Articles/9823/Detect-if-your-program-is-running-inside-a-Virtual is a good starting point. However, inline assembly cannot be included in the x64 version.

**Comment by JASR** [comment]
With a combination of existing win32API commands, LEP and some digging around in the registry, I managed to write a few routines which detect whether the 4D application is running on a VM, what the Host computer is called, and what the host OS is - Only tested on Hyper-V situations.

If anyone wants the code stubs, please eMail me
